# Generated by Django 3.2.6 on 2021-08-13 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('10.00', '10.00'), ('10:30', '10:30'), ('11.00', '11.00'), ('11:30', '11:30'), ('12.00', '12.00'), ('12:30', '12:30'), ('13.00', '13.00'), ('13:30', '13:30'), ('14.00', '14.00'), ('14:30', '14:30'), ('15.00', '15.00'), ('15:30', '15:30'), ('16.00', '16.00'), ('16:30', '16:30')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(related_name='appoinment', to='mainapp.Teacher')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='mainapp.timeslot')),
            ],
        ),
    ]
