# Generated by Django 3.2.6 on 2021-08-14 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_timeslot_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['time']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='student',
        ),
    ]
